export const userConstants={
    LOGIN_REQUEST : 'USER_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
    JOIN_REQUEST : 'USER_JOIN_REEQUEST',
    JOIN_SUCCESS: 'USER_JOIN_SUCCESS',
    JOIN_FAILURE : 'USER_JOIN_FAILURE'
}